theme: jekyll-theme-minimal

title: GRASSMIND
description: Documentation and tutorials for the grassland model.
logo: /uc-grassland-model/assets/images/255571_logo_grassmind-200.jpg
show_downloads: false
